name: "roam-to-git tests.py"

on:
  push:
    branches:
      - master
      - dev 
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 4 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    timeout-minutes: 15
    steps:
      -   uses: actions/checkout@v2
      -   name: Set up Python 3.8
          uses: actions/setup-python@v1
          with:
            python-version: 3.8

      -   name: Setup dependencies
          run: |
            pip install -r requirements.txt
            pip install mypy
      -   name: Run backup
          run: ./tests.py
